trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Dsonar.organization=sandiproy'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    #codeCoverageTool: 'jaCoCo'
    #codeCoverageTool: 'Cobertura'
    #codeCoverageFailIfEmpty: true
    goals: 'package'
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: reportgenerator@4
  inputs:
    reports: 'coverage.html'
    targetdir: 'coveragereport'


- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'my-sample-sonarcloud-conn'
    organization: 'sandiproy'
    scannerMode: 'Other'
    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
