trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    #codeCoverageTool: 'jaCoCo' or 'Cobertura'
    #codeCoverageFailIfEmpty: true
    goals: 'package'
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'


- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Agent.BuildDirectory)/s/target'
    contents: '*.jar' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
    publishLocation: 'Container' # Options: container, filePath
